### ISSUE TITLE
Doesnt work. Throws out an error related to this  "PROSPER FUNDING LLC".

### ISSUE THREAD

**Issue by ecruiser** [MThoma202/prosper-1099-parser#17]
When I see this error msg, it makes me feel like this company has something to do with my financial data. Very suspicious!

2024-12-17T22:29:32.368-08:00 ERROR 34892 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalStateException: First line must match "PROSPER FUNDING LLC".] with root cause

java.lang.IllegalStateException: First line must match "PROSPER FUNDING LLC".
        at com.prosper1099.ConverterController.convertPdfToCsv(ConverterController.java:56) ~[main/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:261) ~[spring-web-6.1.3.jar:6.1.3]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:189) ~[spring-web-6.1.3.jar:6.1.3]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.3.jar:6.1.3]

**Comment by MThoma202** [comment]
Hi @ecruiser,

The error you're seeing is because it's expecting to find the text "PROSPER FUNDING LLC" that should be printed on the top left of the first page of your PDF, and it's not able to find it.

I.e. it's expecting to find this:
<img width="242" alt="Image" src="https://github.com/user-attachments/assets/4f4a6997-8d08-4f36-abf2-4e40f4e37671" />

This is basically a sanity check to confirm it's a valid PDF before attempting to parse the rest of the file.  I should probably update the error message to make it clearer.

This project doesn't support parsing PDF files from other companies.  If you have a PDF containing 1099-B transactions from Prosper and it's not working can you please share more details with me and I could help troubleshoot?  What tax year is it from, and what text does the first page have in the top left corner?

Please feel free to review the code in this project and its history to confirm it's integrity.  Transparency and collaboration are core to open source, and I welcome any feedback or suggestions you might have.

Cheers,
Mark
